2025-03-31 23:36:16,175 - src.scripts.chat_gpt.chat_gpt - ERROR - 'utf-8' codec can't decode byte 0x98 in position 14: invalid start byte
2025-03-31 23:36:16,176 - src.scripts.chat_gpt.chat_gpt - ERROR - Ошибка при отправке сообщения: 'NoneType' object is not subscriptable
2025-03-31 23:36:16,380 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: 'NoneType' object is not subscriptable
2025-03-31 23:36:16,380 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: 'NoneType' object is not subscriptable
2025-03-31 23:36:16,380 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: 'NoneType' object is not subscriptable
2025-03-31 23:40:15,195 - src.scripts.chat_gpt.chat_gpt - ERROR - 'utf-8' codec can't decode byte 0x98 in position 14: invalid start byte
2025-03-31 23:40:15,196 - src.scripts.chat_gpt.chat_gpt - ERROR - Ошибка при отправке сообщения: 'NoneType' object is not subscriptable
2025-03-31 23:40:15,397 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: 'NoneType' object is not subscriptable
2025-03-31 23:40:15,397 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: 'NoneType' object is not subscriptable
2025-03-31 23:40:15,397 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: 'NoneType' object is not subscriptable
2025-03-31 23:47:54,973 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: Error code: 400 - {'error': {'message': "Invalid 'assistant_id': 'йцук'. Expected an ID that contains letters, numbers, underscores, or dashes, but this value contained additional characters.", 'type': 'invalid_request_error', 'param': 'assistant_id', 'code': 'invalid_value'}}
2025-03-31 23:47:54,973 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: Error code: 400 - {'error': {'message': "Invalid 'assistant_id': 'йцук'. Expected an ID that contains letters, numbers, underscores, or dashes, but this value contained additional characters.", 'type': 'invalid_request_error', 'param': 'assistant_id', 'code': 'invalid_value'}}
2025-03-31 23:47:54,973 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: Error code: 400 - {'error': {'message': "Invalid 'assistant_id': 'йцук'. Expected an ID that contains letters, numbers, underscores, or dashes, but this value contained additional characters.", 'type': 'invalid_request_error', 'param': 'assistant_id', 'code': 'invalid_value'}}
2025-04-03 04:44:49,396 - src.scripts.chat_gpt.chat_gpt - ERROR - Ошибка при отправке сообщения: Error code: 403 - {'error': {'code': 'unsupported_country_region_territory', 'message': 'Country, region, or territory not supported', 'param': None, 'type': 'request_forbidden'}}
2025-04-03 04:44:49,957 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: Error code: 403 - {'error': {'code': 'unsupported_country_region_territory', 'message': 'Country, region, or territory not supported', 'param': None, 'type': 'request_forbidden'}}
2025-04-03 04:44:49,957 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: Error code: 403 - {'error': {'code': 'unsupported_country_region_territory', 'message': 'Country, region, or territory not supported', 'param': None, 'type': 'request_forbidden'}}
2025-04-03 04:44:49,957 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: Error code: 403 - {'error': {'code': 'unsupported_country_region_territory', 'message': 'Country, region, or territory not supported', 'param': None, 'type': 'request_forbidden'}}
2025-04-03 04:46:29,788 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: Error code: 400 - {'error': {'message': "Invalid type for 'assistant_id': expected a string, but got null instead.", 'type': 'invalid_request_error', 'param': 'assistant_id', 'code': 'invalid_type'}}
2025-04-03 04:46:29,788 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: Error code: 400 - {'error': {'message': "Invalid type for 'assistant_id': expected a string, but got null instead.", 'type': 'invalid_request_error', 'param': 'assistant_id', 'code': 'invalid_type'}}
2025-04-03 04:46:29,788 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: Error code: 400 - {'error': {'message': "Invalid type for 'assistant_id': expected a string, but got null instead.", 'type': 'invalid_request_error', 'param': 'assistant_id', 'code': 'invalid_type'}}
2025-04-03 04:53:22,051 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: Error code: 400 - {'error': {'message': "Invalid 'assistant_id': 'ChatGPT 4o-mini'. Expected an ID that contains letters, numbers, underscores, or dashes, but this value contained additional characters.", 'type': 'invalid_request_error', 'param': 'assistant_id', 'code': 'invalid_value'}}
2025-04-03 04:53:22,051 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: Error code: 400 - {'error': {'message': "Invalid 'assistant_id': 'ChatGPT 4o-mini'. Expected an ID that contains letters, numbers, underscores, or dashes, but this value contained additional characters.", 'type': 'invalid_request_error', 'param': 'assistant_id', 'code': 'invalid_value'}}
2025-04-03 04:53:22,051 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: Error code: 400 - {'error': {'message': "Invalid 'assistant_id': 'ChatGPT 4o-mini'. Expected an ID that contains letters, numbers, underscores, or dashes, but this value contained additional characters.", 'type': 'invalid_request_error', 'param': 'assistant_id', 'code': 'invalid_value'}}
2025-04-04 02:13:32,853 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: [Errno 111] Connect call failed ('172.22.0.2', 5672)
2025-04-04 02:13:32,853 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: [Errno 111] Connect call failed ('172.22.0.2', 5672)
2025-04-04 02:13:32,853 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: [Errno 111] Connect call failed ('172.22.0.2', 5672)
2025-04-04 12:44:00,809 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: [Errno 111] Connect call failed ('172.22.0.5', 5672)
2025-04-04 12:44:00,809 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: [Errno 111] Connect call failed ('172.22.0.5', 5672)
2025-04-04 12:44:00,809 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: [Errno 111] Connect call failed ('172.22.0.5', 5672)
2025-04-04 12:46:02,734 - src.scripts.chat_gpt.chat_gpt - ERROR - 'utf-8' codec can't decode byte 0xc4 in position 0: invalid continuation byte
2025-04-04 12:46:03,053 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: 'NoneType' object is not subscriptable
2025-04-04 12:46:03,053 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: 'NoneType' object is not subscriptable
2025-04-04 12:46:03,053 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: 'NoneType' object is not subscriptable
2025-04-04 12:52:21,704 - src.scripts.chat_gpt.chat_gpt - ERROR - Error code: 403 - {'error': {'code': 'unsupported_country_region_territory', 'message': 'Country, region, or territory not supported', 'param': None, 'type': 'request_forbidden'}}
2025-04-04 12:52:22,013 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: Error code: 403 - {'error': {'code': 'unsupported_country_region_territory', 'message': 'Country, region, or territory not supported', 'param': None, 'type': 'request_forbidden'}}
2025-04-04 12:52:22,013 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: Error code: 403 - {'error': {'code': 'unsupported_country_region_territory', 'message': 'Country, region, or territory not supported', 'param': None, 'type': 'request_forbidden'}}
2025-04-04 12:52:22,013 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: Error code: 403 - {'error': {'code': 'unsupported_country_region_territory', 'message': 'Country, region, or territory not supported', 'param': None, 'type': 'request_forbidden'}}
2025-04-05 16:29:59,062 - src.scripts.chat_gpt.chat_gpt - ERROR - Ошибка при отправке сообщения: Error code: 403 - {'error': {'code': 'unsupported_country_region_territory', 'message': 'Country, region, or territory not supported', 'param': None, 'type': 'request_forbidden'}}
2025-04-05 16:29:59,746 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: Error code: 403 - {'error': {'code': 'unsupported_country_region_territory', 'message': 'Country, region, or territory not supported', 'param': None, 'type': 'request_forbidden'}}
2025-04-05 16:29:59,746 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: Error code: 403 - {'error': {'code': 'unsupported_country_region_territory', 'message': 'Country, region, or territory not supported', 'param': None, 'type': 'request_forbidden'}}
2025-04-05 16:29:59,746 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: Error code: 403 - {'error': {'code': 'unsupported_country_region_territory', 'message': 'Country, region, or territory not supported', 'param': None, 'type': 'request_forbidden'}}
2025-04-06 11:27:11,058 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: [Errno -2] Name or service not known
2025-04-06 11:27:11,058 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: [Errno -2] Name or service not known
2025-04-06 11:27:11,058 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: [Errno -2] Name or service not known
2025-04-06 11:27:16,076 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: [Errno -2] Name or service not known
2025-04-06 11:27:16,076 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: [Errno -2] Name or service not known
2025-04-06 11:27:16,076 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: [Errno -2] Name or service not known
2025-04-06 11:27:21,091 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: [Errno -2] Name or service not known
2025-04-06 11:27:21,091 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: [Errno -2] Name or service not known
2025-04-06 11:27:21,091 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: [Errno -2] Name or service not known
2025-04-06 11:27:26,098 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: [Errno 111] Connect call failed ('172.22.0.5', 5672)
2025-04-06 11:27:26,098 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: [Errno 111] Connect call failed ('172.22.0.5', 5672)
2025-04-06 11:27:26,098 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: [Errno 111] Connect call failed ('172.22.0.5', 5672)
2025-04-06 11:27:31,103 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: [Errno 111] Connect call failed ('172.22.0.5', 5672)
2025-04-06 11:27:31,103 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: [Errno 111] Connect call failed ('172.22.0.5', 5672)
2025-04-06 11:27:31,103 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: [Errno 111] Connect call failed ('172.22.0.5', 5672)
2025-04-06 23:45:51,138 - src.scripts.spammer.service - ERROR - Telegram server says - Bad Request: can't parse entities: Unsupported start tag "br" at byte offset 19
2025-04-06 23:45:51,197 - src.scripts.spammer.service - ERROR - Telegram server says - Bad Request: can't parse entities: Unsupported start tag "br" at byte offset 19
2025-04-06 23:45:51,255 - src.scripts.spammer.service - ERROR - Telegram server says - Bad Request: can't parse entities: Unsupported start tag "br" at byte offset 19
2025-04-06 23:45:51,305 - src.scripts.spammer.service - ERROR - Telegram server says - Bad Request: can't parse entities: Unsupported start tag "br" at byte offset 19
2025-04-07 10:25:03,690 - src.scripts.antropic.claude_gpt - ERROR - Failed to send message: 'bytes' object has no attribute 'content'
2025-04-07 10:25:04,183 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: 'bytes' object has no attribute 'content'
2025-04-07 10:25:04,183 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: 'bytes' object has no attribute 'content'
2025-04-07 10:25:04,183 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: 'bytes' object has no attribute 'content'
2025-04-07 10:26:59,564 - src.scripts.antropic.claude_gpt - ERROR - Failed to send message: 'bytes' object has no attribute 'content'
2025-04-07 10:26:59,800 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: 'bytes' object has no attribute 'content'
2025-04-07 10:26:59,800 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: 'bytes' object has no attribute 'content'
2025-04-07 10:26:59,800 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: 'bytes' object has no attribute 'content'
2025-04-07 10:34:04,250 - src.scripts.antropic.claude_gpt - ERROR - Failed to send message: 'bytes' object has no attribute 'content'
2025-04-07 10:34:04,617 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: 'bytes' object has no attribute 'content'
2025-04-07 10:34:04,617 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: 'bytes' object has no attribute 'content'
2025-04-07 10:34:04,617 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: 'bytes' object has no attribute 'content'
2025-04-09 16:39:33,766 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:39:33,766 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:39:33,766 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:39:38,775 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:39:38,775 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:39:38,775 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:39:43,788 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:39:43,788 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:39:43,788 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:39:48,801 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:39:48,801 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:39:48,801 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:42:02,768 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:42:02,768 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:42:02,768 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:42:07,783 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:42:07,783 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:42:07,783 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:42:12,797 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:42:12,797 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:42:12,797 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:42:17,808 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:42:17,808 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:42:17,808 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:42:22,819 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:42:22,819 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:42:22,819 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:42:27,831 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:42:27,831 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:42:27,831 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:42:32,841 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:42:32,841 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:42:32,841 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:42:37,854 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:42:37,854 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:42:37,854 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:42:42,869 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:42:42,869 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:42:42,869 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:42:47,878 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:42:47,878 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:42:47,878 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:42:52,897 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:42:52,897 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:42:52,897 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:42:57,906 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:42:57,906 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:42:57,906 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:43:02,917 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:43:02,917 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:43:02,917 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:43:07,926 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:43:07,926 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:43:07,926 - src.scripts.queue.rabbit_queue - ERROR - Ошибка подключения к RabbitMQ: 'RabbitQueue' object has no attribute 'connection'
2025-04-09 16:48:36,546 - src.scripts.queue.worker - ERROR - Error starting parsing worker: 'RabbitQueue' object has no attribute '_lock'
2025-04-09 16:49:06,642 - src.scripts.queue.rabbit_queue - ERROR - Connection attempt 1 failed: maximum recursion depth exceeded
2025-04-09 16:49:06,642 - src.scripts.queue.rabbit_queue - ERROR - Connection attempt 1 failed: maximum recursion depth exceeded
2025-04-09 16:49:06,642 - src.scripts.queue.rabbit_queue - ERROR - Connection attempt 1 failed: maximum recursion depth exceeded
2025-04-09 16:51:41,367 - src.scripts.queue.rabbit_queue - ERROR - Connection attempt 1 failed: maximum recursion depth exceeded
2025-04-09 16:51:41,367 - src.scripts.queue.rabbit_queue - ERROR - Connection attempt 1 failed: maximum recursion depth exceeded
2025-04-09 16:51:41,367 - src.scripts.queue.rabbit_queue - ERROR - Connection attempt 1 failed: maximum recursion depth exceeded
2025-04-09 16:51:46,382 - src.scripts.queue.rabbit_queue - ERROR - Connection attempt 2 failed: maximum recursion depth exceeded
2025-04-09 16:51:46,382 - src.scripts.queue.rabbit_queue - ERROR - Connection attempt 2 failed: maximum recursion depth exceeded
2025-04-09 16:51:46,382 - src.scripts.queue.rabbit_queue - ERROR - Connection attempt 2 failed: maximum recursion depth exceeded
2025-04-09 16:55:12,105 - src.scripts.queue.rabbit_queue - ERROR - Error declaring queue gpt_assistant: PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'gpt_assistant' in vhost '/': received 'true' but current is 'false'
2025-04-09 16:55:12,105 - src.scripts.queue.rabbit_queue - ERROR - Error declaring queue gpt_assistant: PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'gpt_assistant' in vhost '/': received 'true' but current is 'false'
2025-04-09 16:55:12,105 - src.scripts.queue.rabbit_queue - ERROR - Error declaring queue gpt_assistant: PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'gpt_assistant' in vhost '/': received 'true' but current is 'false'
2025-04-09 16:55:12,111 - src.scripts.queue.worker - ERROR - Error starting parsing worker: PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'gpt_assistant' in vhost '/': received 'true' but current is 'false'
2025-04-09 17:00:58,866 - src.scripts.chat_gpt.chat_gpt - ERROR - Ошибка при отправке сообщения: Error code: 403 - {'error': {'code': 'unsupported_country_region_territory', 'message': 'Country, region, or territory not supported', 'param': None, 'type': 'request_forbidden'}}
2025-04-09 17:00:59,391 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: Error code: 403 - {'error': {'code': 'unsupported_country_region_territory', 'message': 'Country, region, or territory not supported', 'param': None, 'type': 'request_forbidden'}}
2025-04-09 17:00:59,391 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: Error code: 403 - {'error': {'code': 'unsupported_country_region_territory', 'message': 'Country, region, or territory not supported', 'param': None, 'type': 'request_forbidden'}}
2025-04-09 17:00:59,391 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: Error code: 403 - {'error': {'code': 'unsupported_country_region_territory', 'message': 'Country, region, or territory not supported', 'param': None, 'type': 'request_forbidden'}}
2025-04-09 17:01:28,771 - src.scripts.chat_gpt.chat_gpt - ERROR - Ошибка при отправке сообщения: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
2025-04-09 17:01:29,332 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
2025-04-09 17:01:29,332 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
2025-04-09 17:01:29,332 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
2025-04-09 18:51:09,715 - src.scripts.chat_gpt.chat_gpt - ERROR - Error code: 403 - {'error': {'code': 'unsupported_country_region_territory', 'message': 'Country, region, or territory not supported', 'param': None, 'type': 'request_forbidden'}}
2025-04-09 18:51:10,364 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: Error code: 403 - {'error': {'code': 'unsupported_country_region_territory', 'message': 'Country, region, or territory not supported', 'param': None, 'type': 'request_forbidden'}}
2025-04-09 18:51:10,364 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: Error code: 403 - {'error': {'code': 'unsupported_country_region_territory', 'message': 'Country, region, or territory not supported', 'param': None, 'type': 'request_forbidden'}}
2025-04-09 18:51:10,364 - src.scripts.queue.rabbit_queue - ERROR - Error processing message: Error code: 403 - {'error': {'code': 'unsupported_country_region_territory', 'message': 'Country, region, or territory not supported', 'param': None, 'type': 'request_forbidden'}}
2025-04-09 19:00:06,526 - src.scripts.midjourney.service - ERROR - Task failed: {'code': 200, 'data': {'task_id': '24694873-55c1-4dc9-84b1-4c17fafe840f', 'model': 'midjourney', 'task_type': 'imagine', 'status': 'failed', 'config': {'service_mode': 'public', 'webhook_config': {'endpoint': '', 'secret': ''}}, 'input': {'bot_id': 0, 'process_mode': 'turbo', 'prompt': 'cat', 'skip_prompt_check': False}, 'output': {'image_url': '', 'image_urls': None, 'temporary_image_urls': None, 'discord_image_url': '', 'actions': [], 'progress': 0, 'intermediate_image_urls': None}, 'meta': {'created_at': '2025-04-09T18:51:22Z', 'started_at': '2025-04-09T18:57:50Z', 'ended_at': '2025-04-09T18:57:51Z', 'usage': {'type': 'point', 'frozen': 700000, 'consume': 0}, 'is_using_private_pool': False, 'model_version': 'unknown', 'process_mode': 'turbo', 'failover_triggered': False}, 'detail': None, 'logs': [], 'error': {'code': 10000, 'raw_message': 'failed to create task: failed to create imagine task', 'message': 'task failed', 'detail': None}}, 'message': 'success'}
2025-04-09 22:42:04,446 - src.scripts.midjourney.service - ERROR - Task failed: {'code': 200, 'data': {'task_id': '92a1aa11-31ab-46a8-95da-a10c7593c93b', 'model': 'midjourney', 'task_type': 'imagine', 'status': 'failed', 'config': {'service_mode': 'public', 'webhook_config': {'endpoint': '', 'secret': ''}}, 'input': {'bot_id': 0, 'process_mode': 'turbo', 'prompt': 'Hello', 'skip_prompt_check': False}, 'output': {'image_url': '', 'image_urls': None, 'temporary_image_urls': None, 'discord_image_url': '', 'actions': [], 'progress': 0, 'intermediate_image_urls': None}, 'meta': {'created_at': '2025-04-09T22:41:56Z', 'started_at': '2025-04-09T22:42:02Z', 'ended_at': '2025-04-09T22:42:02Z', 'usage': {'type': 'point', 'frozen': 700000, 'consume': 0}, 'is_using_private_pool': False, 'model_version': 'unknown', 'process_mode': 'turbo', 'failover_triggered': False}, 'detail': None, 'logs': [], 'error': {'code': 10000, 'raw_message': 'failed to create task: failed to create imagine task', 'message': 'task failed', 'detail': None}}, 'message': 'success'}
2025-04-09 22:42:07,570 - src.scripts.midjourney.service - ERROR - Task failed: {'code': 200, 'data': {'task_id': '92a1aa11-31ab-46a8-95da-a10c7593c93b', 'model': 'midjourney', 'task_type': 'imagine', 'status': 'failed', 'config': {'service_mode': 'public', 'webhook_config': {'endpoint': '', 'secret': ''}}, 'input': {'bot_id': 0, 'process_mode': 'turbo', 'prompt': 'Hello', 'skip_prompt_check': False}, 'output': {'image_url': '', 'image_urls': None, 'temporary_image_urls': None, 'discord_image_url': '', 'actions': [], 'progress': 0, 'intermediate_image_urls': None}, 'meta': {'created_at': '2025-04-09T22:41:56Z', 'started_at': '2025-04-09T22:42:02Z', 'ended_at': '2025-04-09T22:42:02Z', 'usage': {'type': 'point', 'frozen': 700000, 'consume': 0}, 'is_using_private_pool': False, 'model_version': 'unknown', 'process_mode': 'turbo', 'failover_triggered': False}, 'detail': None, 'logs': [], 'error': {'code': 10000, 'raw_message': 'failed to create task: failed to create imagine task', 'message': 'task failed', 'detail': None}}, 'message': 'success'}
2025-04-09 22:42:12,199 - src.scripts.midjourney.service - ERROR - Task failed: {'code': 200, 'data': {'task_id': '92a1aa11-31ab-46a8-95da-a10c7593c93b', 'model': 'midjourney', 'task_type': 'imagine', 'status': 'failed', 'config': {'service_mode': 'public', 'webhook_config': {'endpoint': '', 'secret': ''}}, 'input': {'bot_id': 0, 'process_mode': 'turbo', 'prompt': 'Hello', 'skip_prompt_check': False}, 'output': {'image_url': '', 'image_urls': None, 'temporary_image_urls': None, 'discord_image_url': '', 'actions': [], 'progress': 0, 'intermediate_image_urls': None}, 'meta': {'created_at': '2025-04-09T22:41:56Z', 'started_at': '2025-04-09T22:42:02Z', 'ended_at': '2025-04-09T22:42:02Z', 'usage': {'type': 'point', 'frozen': 700000, 'consume': 0}, 'is_using_private_pool': False, 'model_version': 'unknown', 'process_mode': 'turbo', 'failover_triggered': False}, 'detail': None, 'logs': [], 'error': {'code': 10000, 'raw_message': 'failed to create task: failed to create imagine task', 'message': 'task failed', 'detail': None}}, 'message': 'success'}
2025-04-09 22:42:19,275 - src.scripts.midjourney.service - ERROR - Task failed: {'code': 200, 'data': {'task_id': '92a1aa11-31ab-46a8-95da-a10c7593c93b', 'model': 'midjourney', 'task_type': 'imagine', 'status': 'failed', 'config': {'service_mode': 'public', 'webhook_config': {'endpoint': '', 'secret': ''}}, 'input': {'bot_id': 0, 'process_mode': 'turbo', 'prompt': 'Hello', 'skip_prompt_check': False}, 'output': {'image_url': '', 'image_urls': None, 'temporary_image_urls': None, 'discord_image_url': '', 'actions': [], 'progress': 0, 'intermediate_image_urls': None}, 'meta': {'created_at': '2025-04-09T22:41:56Z', 'started_at': '2025-04-09T22:42:02Z', 'ended_at': '2025-04-09T22:42:02Z', 'usage': {'type': 'point', 'frozen': 700000, 'consume': 0}, 'is_using_private_pool': False, 'model_version': 'unknown', 'process_mode': 'turbo', 'failover_triggered': False}, 'detail': None, 'logs': [], 'error': {'code': 10000, 'raw_message': 'failed to create task: failed to create imagine task', 'message': 'task failed', 'detail': None}}, 'message': 'success'}
2025-04-09 23:21:42,395 - src.scripts.midjourney.service - ERROR - Task failed: {'code': 200, 'data': {'task_id': '531d22d6-1fbc-48ee-afaf-d9fba280c450', 'model': 'midjourney', 'task_type': 'imagine', 'status': 'failed', 'config': {'service_mode': 'public', 'webhook_config': {'endpoint': '', 'secret': ''}}, 'input': {'bot_id': 0, 'process_mode': 'turbo', 'prompt': 'Hello', 'skip_prompt_check': False}, 'output': {'image_url': '', 'image_urls': None, 'temporary_image_urls': None, 'discord_image_url': '', 'actions': [], 'progress': 0, 'intermediate_image_urls': None}, 'meta': {'created_at': '2025-04-09T23:21:09Z', 'started_at': '2025-04-09T23:21:14Z', 'ended_at': '2025-04-09T23:21:32Z', 'usage': {'type': 'point', 'frozen': 700000, 'consume': 0}, 'is_using_private_pool': False, 'model_version': 'unknown', 'process_mode': 'turbo', 'failover_triggered': False}, 'detail': None, 'logs': [], 'error': {'code': 10000, 'raw_message': 'fetch task result failed: task failed', 'message': 'task failed', 'detail': None}}, 'message': 'success'}
